POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbGwiLCJpZCI6IjYyMGM0YTcyNWM1NzIzOGJlZTRkOTFhOCIsImlhdCI6MTY0NTA2NDYxMX0.zhDh5gIekfxOYei3BNbV9TLGmKLGv0YSP9P-Z0AMlJQ

{
    "title": "Hacker News",
    "author": "YCombinator",
    "url": "https://news.ycombinator.com/"
}