DELETE http://localhost:3003/api/blogs/620dcf2c4c3bb4e6382cb5bd
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbGwiLCJpZCI6IjYyMGM0YTcyNWM1NzIzOGJlZTRkOTFhOCIsImlhdCI6MTY0NTA2NDYxMX0.zhDh5gIekfxOYei3BNbV9TLGmKLGv0YSP9P-Z0AMlJQ